[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# Compiler settings
solc_version = '0.8.19'
optimizer = true
optimizer_runs = 200

# Test settings
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]

# RPC endpoints
[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
base_goerli = "https://goerli.base.org"
base_sepolia = "https://sepolia.base.org"
base_mainnet = "https://mainnet.base.org"

# Etherscan API keys
[etherscan]
base_goerli = { key = "${ETHERSCAN_API_KEY}" }
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }
base_mainnet = { key = "${ETHERSCAN_API_KEY}" }

# Deployment settings
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
